st:
  prefix: '[Server][关服提示]'
  start: '开始关服了 %time% 后关服'
  cancel: '取消关服了, 大家继续游玩'
  10: '还有 %time% 秒后关服'
  30: '还有 %time% 秒后关服'
  60: '还有 %time% 秒后关服'
  120: '还有 %time% 秒后关服'
  180: '还有 %time% 秒后关服'